name: GitHub Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: devDougie
          filename: assets/metrics.svg
          base: header, repositories, metadata
          config_theme: dark
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_limit: 5
          plugin_achievements: yes
          plugin_achievements_display: compact
